# 相关配置说明
# favicon: 网站图标
# avatar: 主题用户头像与昵称
# rss: rss订阅
# prevnext: 文章末尾的上一页与下一页
# footer: 页脚信息
# search: 文章搜索

# enable: 是否开启相应功能，可选true || false

# 网站图标
favicon:
  enable: true
  icon: /images/favicon.png
  touch_icon: /images/favicon.png

# 用户头像与昵称
avatar:
  author_photo: /images/avatar.png
  author_nickname: heart's Blog
  path: /

# 文章末尾的上一页与下一页
prevnext:
  enable: true

# 链接信息
link:
  # name: 名称
  # icon: 图标，目前仅支持IconFont部分图标
  # path: 地址
  # target: 跳转方式
  - # 档案
    name: archives
    icon: bookmark
    path: /archives/
  - name: tag
    icon: tags
    path: /categories/
  - name: case
    icon: edit
    path: /repository/
  - name: github
    icon: github
    path: https://github.com/Hearpro
    target: _blank
  # - # rss需安装 hexo-generator-feed 插件
  #   # 具体参照https://github.com/hexojs/hexo-generator-feed
  #   name: rss
  #   icon: rss
  #   path: /atom.xml
  #   target: _blank

# 页脚信息
footer:
  - name: Copyright © Heart 2021
    path: https://github.com/Hearpro

# 文章搜索
search:
  enable: true
  placeholder: 搜索

# repo项目组
repository:
  # name: 名称
  # description: 描述方式
  # path: repo url
  - name: Phrase Generator
    description: 词条生成器
    path: https://github.com/Hearpro/PhraseGenerator
    tags: JavaScript、NodeJs
